version: '2'
services:
 
  #MONGO DB
  mongodb:
    user: root
    image: mongo:latest
    container_name: mongo_db
    restart: always
    command: ["mongod", "--smallfiles"]
    hostname: mongo
    container_name: content-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:rw
    networks:
          gateway:
              aliases:
                  - mongo
  
  microgateway:
    user: root
    build: ./microgateway/.
    ports:
      - "9000:9000"
    environment:
      - CONFIG_DIR=./definitions
      - NODE_ENV=production
      - DEBUG=server.js
    container_name: gateway-service
    volumes:
       - "./data:/home/gateway-service/data"
    depends_on:
      - mongodb
    command: ["npm", "start"]

 #CONTENT SERVICE
  content:
    user: root
    build: ./content/.
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=dev
      - DEBUG=content.js
    container_name: content-service
    volumes:
       - "./data:/home/content-service/data"
    depends_on:
      - mongodb
    command: ["npm", "start"]
 
 #DOCUMENT SERVICE  
  document:
    user: root
    build: ./document/.
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=dev
      - DEBUG=document.js
    container_name: document-service
    volumes:
       - "./data:/home/document-service/data"
    #depends_on:
    #  - rabbitmq
    command: ["npm", "start"]

#NETWORKS  
networks:
  gateway:
  