swagger: '2.0'

info:
  x-ibm-name: content-service
  version: 1.0.0
  title: content-service

schemes:
  - https
host: $(catalog.host)
basePath: /api

consumes:
  - application/json
produces:
  - application/json

#securityDefinitions:
# clientIdHeader:
#   type: apiKey
#   in: header
#   name: X-IBM-Client-Id
# clientSecretHeader:
#   in: "header"
#   name: "X-IBM-Client-Secret"
#   type: "apiKey"


#security:
# -
#   clientIdHeader: []
#   clientSecretHeader: []

x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
#  catalogs:
#    apic-dev:
#      properties:
#        runtime-url: $(TARGET_URL)
#    sb:
#      properties:
#        runtime-url: 'http://localhost:4001'
  properties:
      runtime-url:
        value: 'https://content-service:9001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)

paths:
  /Contents:
    get:
      tags:
        - Content
      summary: |
        Fetch all the Content
      operationId: Content.findAllContent
      parameters:
        - name: filter
          in: query
          description: filter expression provided by calling application
          required: false
          type: string
        - name: access_token
          in: header
          description: token to be passed as a header
          required: false
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            description: Successful Response
            $ref: '#/definitions/Content'
      deprecated: false
    put:
      tags:
        - Content
      summary: |
        Update the Content.
      operationId: Content.updateContent
      parameters:
        - name: content
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/Content'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Successful Response
            $ref: '#/definitions/Content'
      deprecated: false
    patch:
      tags:
        - Content
      summary: |
        Updates WorkFlow of the content.
      operationId: Content.updateWorkflow
      parameters:
        - name: content
          in: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/Content'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Successful Response
            $ref: '#/definitions/Content'
      deprecated: false
    post:
      tags:
        - Content
      summary: |
        Creates the Content.
      operationId: Content.createContent
      parameters:
        - name: content
          in: body
          description: the Content to be created.
          required: true
          schema:
            description: the Content to be created.
            $ref: '#/definitions/Content'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Successful Response
            $ref: '#/definitions/Content'
      deprecated: false


definitions:
  x-any:
    properties: {}
  Content:
    properties:
      id:
        type: number
        format: double
      title:
        description: |
          Title of the Content shown on the UI
        type: string
      name:
        description: |
          Name of the Content to identify the Content
        type: string
      startDate:
        format: date-time
        pattern: "\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}"
        description: |
          Start date of content validity
        type: string
      endDate:
        format: date-time
        pattern: "\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}"
        description: |
          End date of content validity
        type: string
      feature:
        description: |
          Feature to which the content belongs to
        type: string
      format:
        enum:
          - IMAGE
          - VIDEO
          - TEXT
          - PDF
        description: |
          Format of the Content [IMAGE, VIDEO, TEXT,PDF]
        type: string
      version:
        description: |
          Version of the Content
        type: string
      majorVersionFlag:
        description: |
          Specifies if the version being created is a major version
        type: boolean
      assetUrl:
        description: |
          URL of Content. For Image/PDF it could be File system path, For Video
          it could be File Path or WWW URL
        type: string
      text:
        description: |
          Text of the Content
        type: string
      status:
        enum:
          - CREATED
          - SENTFORREVIEW
          - INREVIEW
          - APPROVED
          - REJECTED
          - PUBLISHED
        description: |
          Specifies the approval status of the content
        type: string
      createdBy:
        description: |
          User who created the Content
        type: string
      createdDate:
        format: date-time
        pattern: "\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}"
        description: |
          Created date of the Content
        type: string
      updatedDate:
        format: date-time
        pattern: "\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}"
        description: |
          Updated date/published date of the Content
        type: string
      updatedBy:
        description: |
          User who updated the Content
        type: string
      locale:
        description: |
          locale of the Content
        type: string
      extendedData:
        description: |
          Extended Data to hold any format data associated to the Content
        type: object
      workflowList:
        description: >
          List containing information about diffrent workflow states content was
          passed through
        type: array
        items:
          $ref: '#/definitions/WorkFlow'
    additionalProperties: false
  WorkFlow:
    properties:
      userName:
        description: |
          Reviewer who initiated workflow transition
        type: string
      role:
        description: |
          Role of the reviewer who initiated workflow transiton
        type: string
      comment:
        description: |
          Comments by reviewer
        type: string
      date:
        format: date-time
        pattern: "\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}"
        description: |
          Time when the state transition happened
        type: string
      id:
        type: number
        format: double
    additionalProperties: false

